// This file is automatically generated by ABP framework to use MVC Controllers from CSharp
using System;
using System.Threading.Tasks;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Http.Client;
using Volo.Abp.Http.Modeling;
using Volo.Abp.DependencyInjection;
using Volo.Abp.Http.Client.ClientProxying;
using Volo.Abp.Identity;

// ReSharper disable once CheckNamespace
namespace Volo.Abp.Identity.ClientProxies;

[Dependency(ReplaceServices = true)]
[ExposeServices(typeof(IIdentityExternalLoginAppService), typeof(IdentityExternalLoginClientProxy))]
public partial class IdentityExternalLoginClientProxy : ClientProxyBase<IIdentityExternalLoginAppService>, IIdentityExternalLoginAppService
{
    public virtual async Task CreateOrUpdateAsync()
    {
        await RequestAsync(nameof(CreateOrUpdateAsync));
    }
}
